name: LG Channels M3U/EPG Generator

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'lgchannels_generator.py'
      - '.github/workflows/lgchannels.yml'

jobs:
  generate-m3u-epg:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Create output directory
      run: mkdir -p lgchannels_playlist
    
    - name: Run LG Channels M3U/EPG Generator
      run: python lgchannels_generator.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add lgchannels_playlist/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update LG Channels M3U and EPG data" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
